export type Field = { name: string; type?: "text" | "textarea" | "rich" | "number" | "boolean" | "status" | "json" | "image" | "products"; required?: boolean }

export const entities: Record<string, { api: string; title: string; fields: Field[] }> = {
  pages: { api: "pages", title: "pages", fields: [{ name: "title", required: true }, { name: "slug", required: true }, { name: "excerpt", type: "textarea" }, { name: "content", type: "rich" }, { name: "hero_image", type: "image" }, { name: "mobile_image", type: "image" }, { name: "image_alt" }, { name: "seo", type: "json" }, { name: "status", type: "status" }, { name: "sort_order", type: "number" }] },
  brands: { api: "brands", title: "brands", fields: [{ name: "name", required: true }, { name: "slug", required: true }, { name: "title" }, { name: "subtitle" }, { name: "short_description", type: "textarea" }, { name: "content", type: "rich" }, { name: "logo", type: "image" }, { name: "hero_image", type: "image" }, { name: "mobile_image", type: "image" }, { name: "image_alt" }, { name: "products", type: "products" }, { name: "seo", type: "json" }, { name: "status", type: "status" }, { name: "sort_order", type: "number" }] },
  articles: { api: "articles", title: "articles", fields: [{ name: "title", required: true }, { name: "slug", required: true }, { name: "excerpt", type: "textarea" }, { name: "content", type: "rich" }, { name: "featured_image", type: "image" }, { name: "image_alt" }, { name: "author" }, { name: "seo", type: "json" }, { name: "status", type: "status" }] },
  banners: { api: "banners", title: "banners", fields: [{ name: "internal_name", required: true }, { name: "title" }, { name: "subtitle" }, { name: "desktop_image", type: "image" }, { name: "mobile_image", type: "image" }, { name: "image_alt" }, { name: "placement", required: true }, { name: "button_text" }, { name: "button_url" }, { name: "active", type: "boolean" }, { name: "sort_order", type: "number" }] },
  faq: { api: "faq", title: "faq", fields: [{ name: "question", required: true }, { name: "answer", type: "rich", required: true }, { name: "group" }, { name: "active", type: "boolean" }, { name: "sort_order", type: "number" }] },
  navigation: { api: "navigation-items", title: "navigation", fields: [{ name: "label", required: true }, { name: "url", required: true }, { name: "active", type: "boolean" }, { name: "sort_order", type: "number" }] },
  footer: { api: "footer-sections", title: "footer", fields: [{ name: "title", required: true }, { name: "content", type: "rich" }, { name: "active", type: "boolean" }, { name: "sort_order", type: "number" }] },
  settings: { api: "settings", title: "settings", fields: [{ name: "key", required: true }, { name: "value", type: "json", required: true }] },
  seo: { api: "settings", title: "seo", fields: [{ name: "key", required: true }, { name: "value", type: "json", required: true }] },
  home: { api: "sections", title: "home", fields: [{ name: "internal_name", required: true }, { name: "type", required: true }, { name: "title" }, { name: "subtitle" }, { name: "content", type: "rich" }, { name: "active", type: "boolean" }, { name: "sort_order", type: "number" }] },
}
